### ISSUE TITLE
v1 / v2 render table dropdown entries on demand

### ISSUE THREAD

**Issue by JuliusRuppert** [DominoKit/domino-ui#905] opened 2024-01-05 09:07 UTC
When having huge tables with several dropdown menus in most of the cells, the initial load of a table takes long.
Maybe this could be reduced by rendering the dropdown entries on demand, e.g. when a user clicks on it. This functionality could be enabled and disabled so it will be applied on selected tables only.

**Comment by vegegoku** [comment] 2024-01-14 20:14
Reading this again I dont I can have a clear idea what needs to be done here unless I understand the use case, sharing a small and explain it a little bit more can be helpful.

**Comment by JuliusRuppert** [comment] 2024-01-19 16:28
In our case we are combining dataTables with Selects. In some cases the tables have more than 80 columns and  about hundreds of rows. Most of them have Selects with multiple options.
When loading such a big table, the rendering time will take up to minutes.

Therefore our request is to render the selects when they are klicked, if possible.
With this improvement even weak devices are able to display tables containing Selects in a reasonable amount of time.

Please see our following code example for demonstration that will render the table on clicking the refresh button.

<details>
  <summary>example code</summary>

``` Java
import com.google.gwt.core.client.EntryPoint;
import elemental2.dom.Event;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import org.dominokit.domino.ui.cards.Card;
import org.dominokit.domino.ui.cards.HeaderAction;
import org.dominokit.domino.ui.datatable.ColumnConfig;
import org.dominokit.domino.ui.datatable.DataTable;
import org.dominokit.domino.ui.datatable.TableConfig;
import org.dominokit.domino.ui.datatable.store.LocalListDataStore;
import org.dominokit.domino.ui.forms.Select;
import org.dominokit.domino.ui.forms.SelectOption;
import org.dominokit.domino.ui.icons.Icons;
import org.dominokit.domino.ui.layout.Layout;
import org.dominokit.domino.ui.style.ColorScheme;

public class TableSelects implements EntryPoint {

    private LocalListDataStore<DataObject> localListDataStore;

    private DataTable<DataObject> table;

    private final TableConfig<DataObject> tableConfig = new TableConfig<>();

    private final Card card = Card.create();

    private final static int NUMBER_OF_COLUMNS = 20;

    private final static int NUMBER_OF_ROWS = 150;
    
    private final static int NUMBER_OF_SELECT_ENTRIES = 30;

    public static int reloadCounter = 0;

    @Override
    public void onModuleLoad() {

        Layout layout = Layout.create("Select rendering").show(ColorScheme.AMBER);

        initTableConfig();

        localListDataStore = new LocalListDataStore<>();

        table = new DataTable<>(tableConfig, localListDataStore).noStripes();

        List<DataObject> data = createTableData();

        card.addHeaderAction(new HeaderAction(Icons.MDI_ICONS.refresh_mdi()).addClickListener((Event evt) -> {
            card.getBody().clearElement();

            localListDataStore = new LocalListDataStore<>();
            table = new DataTable<>(tableConfig, localListDataStore);

            card.appendChild(table);
            localListDataStore.setData(data);
        }));
        
        
        card.appendChild(table);

        layout.getContentPanel().appendChild(card);

    }

    private void initTableConfig() {
        addTableConfigColumns();
    }

    private void addTableConfigColumns() {
        for (int i = 1; i <= NUMBER_OF_COLUMNS; i++) {
            tableConfig.addColumn(ColumnConfig.<DataObject>create("column" + i, "column" + i)
                    .setCellRenderer(
                            cell -> createSelectRenderer().element())
            );
        }
    }

    private Select<String> createSelectRenderer() {
        Select<String> select = Select.<String>create();
        for (int i = 0; i <= NUMBER_OF_SELECT_ENTRIES; i++) {
            select.appendChild(SelectOption.create("Value " + i, String.valueOf(i)));
        }
        select.selectAt(0);
        return select;

    }

    private List<DataObject> createTableData() {

        List<DataObject> data = new ArrayList<>();

        for (int i = 0; i <= NUMBER_OF_ROWS; i++) {
            DataObject object = new DataObject()
                    .addDataObject("index", (i));
            for (int j = 1; j <= NUMBER_OF_COLUMNS; j++) {
                object.addDataObject("column" + j, 1);
            }
            data.add(object);
        }
        return data;
    }
    
    private static class DataObject {

        private final HashMap<String, Object> keyValuePair = new HashMap<>();

        public DataObject addDataObject(String key, Object value) {
            keyValuePair.put(key, value);
            return this;
        }

        public Object getValue(String key) {
            return keyValuePair.get(key);
        }
    }
}

```

**Comment by vegegoku** [comment] 2024-01-28 11:17
This means you need the selects to be lazy initialized, this might be a complete new component since this is a big change, think of how I would set a value for the select while its options are not yet added, so I we wont know if the value is acceptable or not, this will force us to initialize the selects anyway,  there might be something in the middle we can implement but that need further investigation and testing, so meanwhile I guess you might try some other workarounds, for example :

1. Use suggest box which can be made to load the options while the user is typing, but the problem is that there will be fixed menu of options unless the user triggers the suggestion and can accept any value.
2. Use editable table rows, this means you normally would render all the fields values as a normal text instead of selects, only when the user clicks on the row you will make it editable and only then render the selects, so with this you will be only render the menus on demand.
3. Build a custom cell that will look like a select but will only render a select on click or something, you might need to manually open the select menu when the cell is clicked, this is somehow like and editable row but on a cell level.

**Closed** 2024-04-09 10:27 UTC
