### ISSUE TITLE
Carousel and submenu issue

### ISSUE THREAD

**Issue by masterdany88** [DominoKit/domino-ui#103] opened 2018-09-03 07:30 UTC
UI issues. 
When you open submenu,the whole shell goes down for few px

And carousel / slider goes partially above left side navigation (the dots).
![screenshot_2018-09-03-08-24-42](https://user-images.githubusercontent.com/1161910/44973133-cc57f000-af5b-11e8-9e97-6eb5a75fd0cb.png)
![screenshot_2018-09-03-08-24-08](https://user-images.githubusercontent.com/1161910/44973143-d0840d80-af5b-11e8-951b-945a829116f6.png)

**Comment by vegegoku** [comment] 2018-09-03 08:13
The 2nd one is fixed but we still need to puplish a new site, currently we are updating the demo app to remove the deprecated apis.

The first one is not clear, can you please show exactly what is the issue?

**Comment by masterdany88** [comment] 2018-09-03 09:42
White space between browser window and top bar of app shell cames when showing submenu

**Comment by vegegoku** [comment] 2018-09-03 10:35
Found the issue, it is caused by the search bar, fixed by making the search hidden by default
Thanks for reporting

**Comment by vegegoku** [comment] 2018-09-21 07:31
already fixed in the latest snapshot

**Closed by vegegoku** 2018-09-21 07:31 UTC
Labels: bug
