### ISSUE TITLE
[Form fields] SelectHeaderFilter - dropdown not visible

### ISSUE THREAD

**Issue by doctorj** [DominoKit/domino-ui#308] opened 2019-12-01 18:12 UTC
Select in table header - when clicked, dropdown opens behind table body and is not visible.

**Comment by vegegoku** [comment] 2019-12-02 08:36
I have been testing this and could not reproduce

**Comment by vegegoku** [comment] 2019-12-02 13:50
I was able to reproduce the case and should be fixed very soon.

**Comment by vegegoku** [comment] 2019-12-03 15:52
the fix made more issues with the datatable, will need to find a better solution, most likely will need to change how we open the popup.

**Closed** 2019-12-13 14:47 UTC
Labels: bug
