### ISSUE TITLE
Add Virtual Scrolling to DataTable

### ISSUE THREAD

**Issue by Ri-gers** [DominoKit/domino-ui#956] opened 2024-08-26 09:34 UTC
When using the DataTable with some larger amount of rows (starting from a few hundred already), rendering time respectively performance gets progressively worse pretty quickly (even operations like expanding/collapsing RowDetails might take seconds depending on the amount of rows, the UI just feels clunky then). This could be avoided by using Virtual Scrolling which basically lets the table only render visible rows. Rows which are not in the current viewport will get removed from the DOM thus drastically improving performance.

**Comment by vegegoku** [comment] 2024-08-26 10:39
Duplicate of https://github.com/DominoKit/domino-ui/issues/725

**Closed** 2024-12-22 05:46 UTC
Labels: duplicate
